spring.application.name=expense-tracking-system


spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracking_system
spring.datasource.username=root
spring.datasource.password=Haidari369
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt-secret= 3a4f499dd0144cbbd6449c9c1e83b9e9dd9c4e8b500474f0d63de99b8fa23ddf
app.jwt-expiration-milliseconds= 3600000

logging.level.org.springframework.security=DEBUG
